image: atlassian/default-image:2

pipelines:
  branches:
    master:
      - step:
          name: "Build and push"
          caches:
            - maven
          services:
            - docker
          script:
            - mvn -B -f pom.xml clean package -DskipTests
            - REPO="crimsy/sb-backend"
            - VERSION="${BITBUCKET_COMMIT}"
            - echo ${DOCKERHUB_PASSWORD} | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
            - docker build -t ${REPO} .
            - docker tag ${REPO} ${REPO}:${VERSION}
            - docker push ${REPO}
      - step:
          name: "Deploy to PROD"
          deployment: production
          script:
            - envsubst < k8s/deployment.tpl.yaml > k8s/deployment.yaml
            - pipe: atlassian/kubectl-run:1.1.3
              variables:
                KUBE_CONFIG: $KUBE_CONFIG
                KUBECTL_COMMAND: 'apply'
                RESOURCE_PATH: 'k8s/deployment.yaml'

    develop:
      - step:
          name: "Build and push"
          caches:
            - maven
          services:
            - docker
          script:
            - mvn -B -f pom.xml clean package -DskipTests
            - REPO="crimsy/sb-backend"
            - VERSION="${BITBUCKET_COMMIT}"
            - echo ${DOCKERHUB_PASSWORD} | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
            - docker build -t ${REPO}:${VERSION} .
            - docker push ${REPO}:${VERSION}
      - step:
          name: "Deploy to dev"
          deployment: production
          script:
            - envsubst < k8s/deployment.dev.tpl.yaml > k8s/deployment.yaml
            - pipe: atlassian/kubectl-run:1.1.3
              variables:
                KUBE_CONFIG: $KUBE_CONFIG
                KUBECTL_COMMAND: 'apply'
                RESOURCE_PATH: 'k8s/deployment.yaml'